const STATE_ACTIONS = {
	ADD_TASK: 'ADD_TASK',
	ADD_LIST: 'ADD_LIST',
	UPDATE_LIST: 'UPDATE_LIST',
	UPDATE_LIST_ORDER: 'UPDATE_LIST_ORDER',
	UPDATE_BOOKMARK: 'UPDATE_BOOKMARK'
};

const INVITATION_DEFAULT_MESSAGE = "I'm working on this project in Trello and wanted to share it with you!";

export { STATE_ACTIONS, INVITATION_DEFAULT_MESSAGE };
