const STATE_ACTIONS = {
	ADD_TASK: 'ADD_TASK',
	ADD_LIST: 'ADD_LIST',
	UPDATE_LIST: 'UPDATE_LIST',
	UPDATE_LIST_ORDER: 'UPDATE_LIST_ORDER',
	UPDATE_BOOKMARK: 'UPDATE_BOOKMARK'
};

export { STATE_ACTIONS };
